# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/notes',
                'doc_host': 'https://alexlewzey.github.io',
                'git_url': 'https://github.com/alexlewzey/notes',
                'lib_path': 'notes'},
  'syms': {'notes.core': {'notes.core.foo': ('core.html#foo', 'notes/core.py')}}}
